Name=zero-lliurex-traduia
Name[es]=Instalador de TraduIA
Name[ca@valencia]=Instal·lador de TraduIA
Name[qcv]=Instal·lador de TraduIA
Name[ca_ES]=Instal·lador de TraduIA
Comment=Realtime translation for classroom
Comment[es]=Traducción en tiempo real para aulas
Comment[ca@valencia]=Traducció en temps real per a les aules
Comment[qcv]=Traducció en temps real per a les aules
Comment[ca_ES]=Traducció en temps real per a les aules
Icon=traduia
Category=Software
ScriptPath=zero-lliurex-traduia.zmd
Groups=sudo;admins;teachers
Using=pkexec
#Service=True
#Modal=True
#Show=False