#!/bin/bash

# Configuración de gettext
export TEXTDOMAIN="zero-lliurex-traduia"
export TEXTDOMAINDIR="/usr/share/locale"

# Función para simplificar la llamada a gettext
_() {
    gettext "$1"
}

ACTION="$1"

function remove_models(){
    models='/usr/lib/ai/traduia_models'
    if [ -e "$models" ]; then
        rm -rf "$models"
    fi
    venv='/usr/lib/traduia/venv'
    if [ -e "$venv" ]; then
        rm -rf "$venv"
    fi
    d='/usr/lib/traduia'
    if [ -d "$d" ]; then
        rmdir "$d" || true
    fi
}

case $ACTION in

    preInstall)
        if [ -f "/tmp/.traduia_install_mode" ]; then
            mode=$(cat /tmp/.traduia_install_mode )
            chown root:root /tmp/.traduia_install_mode
        else
            mode=""
        fi
        while [ ! -n "$mode" ]; do
            # Definimos las etiquetas traducidas para el UI
            CLIENT_LABEL=$(_ "Client")
            SERVER_LABEL=$(_ "Server")
            
            # kdialog muestra las etiquetas traducidas
            selected=$(kdialog --title "$(_ "Mode selector")" --combobox "$(_ "Install mode:")" "$CLIENT_LABEL" "$SERVER_LABEL")
            ret=$?
            if [ $ret -eq 1 ]; then
                exit 1
            fi
            
            # Mapeamos la selección a un valor interno neutro (en inglés)
            if [ "$selected" == "$SERVER_LABEL" ]; then
                mode="Server"
            else
                mode="Client"
            fi
        done
        # Guardamos el valor interno, no el traducido
        echo "$mode" > /tmp/.traduia_install_mode
    ;;

    postInstall)
        mode=$(cat /tmp/.traduia_install_mode)
        if [ -n "$mode" ]; then
            if [ "$mode" == "Server" ]; then
                # Aquí la comparación con "Server" sigue funcionando
                echo "$(_ "Downloading models...")"
                /usr/sbin/install-models-traduia
                echo "$(_ "Setting server desktop")"
                sed -i -e 's|noDisplay=true|NoDisplay=false|i' /usr/share/applications/traduia-server.desktop
            else
               remove_models
            fi
        fi
        rm -f /tmp/.traduia_install_mode || true
    ;;
    remove)
        rm -f /tmp/.traduia_install_mode || true
        apt-get remove -y traduia
        TEST=$( dpkg-query -s  traduia 2> /dev/null| grep Status | cut -d " " -f 4 )
        if [ "$TEST" == 'installed' ];then
            exit 1
        else
            remove_models
        fi
    ;;	
esac
