#!/bin/bash


ACTION="$1"

function remove_models(){
    models='/usr/lib/ai/traduia_models'
    if [ -e "$models" ]; then
	rm -rf "$models"
    fi
    venv='/usr/lib/traduia/venv'
    if [ -e "$venv" ]; then
	rm -rf "$venv"
    fi
    d='/usr/lib/traduia'
    if [ -d "$d" ]; then
	rmdir "$d" || true
    fi
}

case $ACTION in

    preInstall)
    ;;

    postInstall)
        mode=""
        while [ ! -n "$mode" ]; do
            mode=$(kdialog --title "Mode selector" --combobox "Install mode:" "Client" "Server")
        done
        if [ -n "$mode" ]; then
            if [ "$mode" == "Server" ]; then
                echo "Downloading models..."
                /usr/sbin/install-models-traduia
            else
               remove_models
            fi
        fi
    ;;
    remove)
	apt-get remove -y traduia
	TEST=$( dpkg-query -s  traduia 2> /dev/null| grep Status | cut -d " " -f 4 )
	if [ "$TEST" == 'installed' ];then
	    exit 1
	else
            remove_models
	fi
    ;;	
esac