#!/bin/bash

# Zero-script de TraduIA: dispatcher hacia traduia-config.
# El ciclo de vida del paquete (apt) entre preInstall y postInstall lo
# realiza el script superior de zero-center; en remove lo hace
# traduia-config remove.

case "$1" in
    preInstall)  /usr/sbin/traduia-config preinstall ;;
    postInstall) /usr/sbin/traduia-config postinstall ;;
    remove)      /usr/sbin/traduia-config remove ;;
    *)           exit 1 ;;
esac
