[DEFAULT]
pristine-tar = False
#cleaner = fakeroot debian/rules clean

[buildpackage]
export-dir = ../build-area
debian-branch = jammy_new_parameters_hotwords_noise
upstream-tree = jammy_new_parameters_hotwords_noise
