[DEFAULT]
pristine-tar = False
#cleaner = fakeroot debian/rules clean

[buildpackage]
export-dir = ../build-area
debian-branch = debian/jammy_new_local_models
upstream-tree = debian/jammy_new_local_models
