[DEFAULT]
pristine-tar = False
#cleaner = fakeroot debian/rules clean

[buildpackage]
export-dir = ../build-area
debian-branch = testing/jammy_feature_offline-models_w_hotwords-noise_w_easy
upstream-tree = testing/jammy_feature_offline-models_w_hotwords-noise_w_easy
